 DROP TABLE IF EXISTS Flat;
 DROP TABLE IF EXISTS PriceHistory;

 CREATE TABLE Flat (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 CountRooms INT,
 Link VARCHAR(255),
 Area FLOAT(3)
 );

 CREATE TABLE PriceHistory (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 FlatId INT NOT NULL,
 Price DECIMAL(13,5),
 Date DATE,
 CONSTRAINT FK_PriceHistory_FlatId_Flat_ID FOREIGN KEY(FlatId)
 REFERENCES Flat (ID)
 ON DELETE CASCADE
 ON UPDATE CASCADE
 );
